config/routes.rb
Rails.application.routes.draw do
  resources :todos
  root      'todos#index'
end

app/models/todo.rb
class Todo < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy]

  # GET /todos
  # GET /todos.json
  def index
    @todos = Todo.all
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        flash[:success] = 'Todo was successfully created.'
        format.html { redirect_to @todo }
        format.json { render :show, status: :created, location: @todo }
      else
        flash[:danger] = 'There was a problem creating the todo.'
        format.html { render :new }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        flash[:success] = 'Todo was successfully updated.'
        format.html { redirect_to @todo }
        format.json { render :show, status: :ok, location: @todo }
      else
        flash[:danger] = 'There was a problem updating the todo.'
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url, notice: 'Todo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_params
      params.require(:todo).permit(:title, :notes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'shared/navigation' %>

    <div id="main-container" class="container">
      <div class="row">
        <div class="col-xs-12">
          <% flash.each do |name, msg| -%>
            <%= content_tag :div, msg, class: "alert alert-#{name}" %>
          <% end -%>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-3">
          <h3>Tealeaf Academy Todo</h3>
        </div>
        <div class="col-xs-9">
          <%= yield %>
        </div>
      </div>
    </div>

</body>
</html>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <a href="/" class="navbar-brand">Tealeaf Todo</a>
    </div>

    <ul class="nav navbar-nav navbar-right">
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Menu <span class="caret"></span></a>
        <ul class="dropdown-menu" role="menu">
          <li><a href="#">Login</a></li>
          <li class="divider"></li>
          <li><%= link_to 'Create a todo', new_todo_path %></li>
        </ul>
      </li>
    </ul>

  </div>
</nav>

app/views/todos/_form.html.erb
<%= form_for(@todo, html: {class: 'form-horizontal'}) do |f| %>
<% if @todo.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

  <ul>
    <% @todo.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field form-group">
  <%= f.label :title, class: 'col-sm-2 control-label' %>
  <div class="col-sm-10">
    <%= f.text_field :title, class: 'form-control' %>
  </div>
</div>
<div class="field form-group">
  <%= f.label :notes, class: 'col-sm-2 control-label' %>
  <div class="col-sm-10">
    <%= f.text_area :notes, class: 'form-control' %>
  </div>
</div>
<div class="actions form-group">
  <div class="col-sm-offset-2 col-sm-10">
    <%= f.submit %>
  </div>
</div>
<% end %>

app/views/todos/edit.html.erb
<h1>Editing Todo</h1>

<%= render 'form' %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>

app/views/todos/index.html.erb
<p id="notice"><%= notice %></p>

<ul class="nav nav-tabs" role="tablist">
  <li class="active"><%= link_to 'View list', todos_path %></li>
  <li><%= link_to 'New todo', new_todo_path %></li>
</ul>
<h1>Listing Todos</h1>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todos.each do |todo| %>
      <tr>
        <td>

        <span class="has-tooltip" data-toggle="tooltip" title="<%= "Created on #{todo.created_at.strftime("%m/%e/%Y at %w:%M %p")}, Last modified on #{todo.updated_at.strftime("%m/%e/%Y at %w:%M %p")}" %>">
          <%= todo.title %>
        </span>

        </td>
        <td>

        <% if todo.notes? %>
          <button type="button" class="btn btn-link has-popover" data-toggle="popover" title="Notes" data-content="<%= todo.notes %>">View notes (popover)</button>
        <% end %>

        <% if todo.notes? %>
          <!-- Button trigger modal -->
          <button class="btn btn-link" data-toggle="modal" data-target="#todo-<%= todo.id %>-notes">
            View notes
          </button>

          <!-- Modal -->
          <div class="modal fade" id="todo-<%= todo.id %>-notes" tabindex="-1" role="dialog" aria-labelledby="todo-<%= todo.id %>-label" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <h4 class="modal-title" id="todo-<%= todo.id %>-label">Notes</h4>
                </div>
                <div class="modal-body">
                  <%= todo.notes %>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                </div>
              </div>
            </div>
          </div>
        <% end %>

        </td>
        <td><%= link_to 'Show', todo, class: 'btn btn-primary btn-xs' %></td>
        <td><%= link_to 'Edit', edit_todo_path(todo), class: 'btn btn-info btn-xs' %></td>
        <td><%= link_to 'Destroy', todo, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to new_todo_path, class: 'btn btn-success' do %>
  <i class="glyphicon glyphicon-plus"></i> New Todo
<% end %>

app/views/todos/new.html.erb
<ul class="nav nav-tabs" role="tablist">
  <li><%= link_to 'View list', todos_path %></li>
  <li class="active"><%= link_to 'New todo', new_todo_path %></li>
</ul>

<h1>New Todo</h1>

<%= render 'form' %>

<%= link_to 'Back', todos_path %>

app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @todo.title %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @todo.notes %>
</p>

<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>